# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(1045, 463)
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.bSelectMedia = QtWidgets.QPushButton(self.centralwidget)
        self.bSelectMedia.setGeometry(QtCore.QRect(10, 10, 141, 34))
        self.bSelectMedia.setObjectName("bSelectMedia")
        self.cbSelectLang = QtWidgets.QComboBox(self.centralwidget)
        self.cbSelectLang.setGeometry(QtCore.QRect(200, 230, 92, 32))
        self.cbSelectLang.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.cbSelectLang.setObjectName("cbSelectLang")
        self.labelSelectLang = QtWidgets.QLabel(self.centralwidget)
        self.labelSelectLang.setGeometry(QtCore.QRect(20, 230, 141, 31))
        self.labelSelectLang.setObjectName("labelSelectLang")
        self.bConvert = QtWidgets.QPushButton(self.centralwidget)
        self.bConvert.setEnabled(False)
        self.bConvert.setGeometry(QtCore.QRect(200, 270, 341, 34))
        self.bConvert.setObjectName("bConvert")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 320, 1021, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.labelCurrentOperation = QtWidgets.QLabel(self.centralwidget)
        self.labelCurrentOperation.setGeometry(QtCore.QRect(170, 330, 871, 41))
        self.labelCurrentOperation.setText("")
        self.labelCurrentOperation.setObjectName("labelCurrentOperation")
        self.bOpenOutputFolder = QtWidgets.QPushButton(self.centralwidget)
        self.bOpenOutputFolder.setGeometry(QtCore.QRect(560, 270, 241, 34))
        self.bOpenOutputFolder.setObjectName("bOpenOutputFolder")
        self.bSelectOutputFolder = QtWidgets.QPushButton(self.centralwidget)
        self.bSelectOutputFolder.setGeometry(QtCore.QRect(10, 180, 141, 34))
        self.bSelectOutputFolder.setObjectName("bSelectOutputFolder")
        self.qleOutputFolder = QtWidgets.QLineEdit(self.centralwidget)
        self.qleOutputFolder.setGeometry(QtCore.QRect(160, 180, 861, 32))
        self.qleOutputFolder.setText("")
        self.qleOutputFolder.setReadOnly(True)
        self.qleOutputFolder.setObjectName("qleOutputFolder")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(160, 10, 871, 161))
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.qlwListFilesSelected = QtWidgets.QListWidget(self.groupBox)
        self.qlwListFilesSelected.setGeometry(QtCore.QRect(10, 30, 851, 121))
        self.qlwListFilesSelected.setObjectName("qlwListFilesSelected")
        self.bRemoveFile = QtWidgets.QPushButton(self.centralwidget)
        self.bRemoveFile.setGeometry(QtCore.QRect(10, 50, 141, 34))
        self.bRemoveFile.setObjectName("bRemoveFile")
        self.labelProgressFileIndex = QtWidgets.QLabel(self.centralwidget)
        self.labelProgressFileIndex.setGeometry(QtCore.QRect(30, 330, 131, 41))
        self.labelProgressFileIndex.setText("")
        self.labelProgressFileIndex.setObjectName("labelProgressFileIndex")
        self.bCancel = QtWidgets.QPushButton(self.centralwidget)
        self.bCancel.setGeometry(QtCore.QRect(470, 370, 108, 36))
        self.bCancel.setObjectName("bCancel")
        self.chbxOpenOutputFilesAuto = QtWidgets.QCheckBox(self.centralwidget)
        self.chbxOpenOutputFilesAuto.setGeometry(QtCore.QRect(560, 230, 351, 32))
        self.chbxOpenOutputFilesAuto.setChecked(True)
        self.chbxOpenOutputFilesAuto.setObjectName("chbxOpenOutputFilesAuto")
        window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1045, 34))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(window)
        self.statusbar.setObjectName("statusbar")
        window.setStatusBar(self.statusbar)
        self.actionLicense = QtWidgets.QAction(window)
        self.actionLicense.setObjectName("actionLicense")
        self.actionAbout_pyTranscriber = QtWidgets.QAction(window)
        self.actionAbout_pyTranscriber.setObjectName("actionAbout_pyTranscriber")
        self.menuAbout.addAction(self.actionLicense)
        self.menuAbout.addAction(self.actionAbout_pyTranscriber)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "pyTranscriber - v1.3 - 18/10/2019"))
        self.bSelectMedia.setText(_translate("window", "Select file(s)"))
        self.labelSelectLang.setText(_translate("window", "Audio Language"))
        self.bConvert.setText(_translate("window", "Transcribe Audio / Generate Subtitles"))
        self.bOpenOutputFolder.setText(_translate("window", "Open Output Folder"))
        self.bSelectOutputFolder.setText(_translate("window", "Output Location"))
        self.groupBox.setTitle(_translate("window", "&List of files to generate transcribe audio / generate subtitles"))
        self.bRemoveFile.setText(_translate("window", "Remove file(s)"))
        self.bCancel.setText(_translate("window", "Cancel"))
        self.chbxOpenOutputFilesAuto.setText(_translate("window", "Open output transcription files automatically"))
        self.menuAbout.setTitle(_translate("window", "Abo&ut"))
        self.actionLicense.setText(_translate("window", "&License"))
        self.actionAbout_pyTranscriber.setText(_translate("window", "&About pyTranscriber"))
